# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5983f45f835e0906c2dfdb8a9038d8de"
application_url = "https://excel-protocols-strengths-necessary.trycloudflare.com"
embedded = true
name = "bad-ship-gallery-staging"
handle = "bad-ship-gallery-staging"

[build]
include_config_on_deploy = true
dev_store_url = "badsheepyarn-gallery.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://excel-protocols-strengths-necessary.trycloudflare.com/auth/callback",
  "https://excel-protocols-strengths-necessary.trycloudflare.com/auth/shopify/callback",
  "https://excel-protocols-strengths-necessary.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
